import { useEffect, useMemo, useState } from 'react';
import { api, getAdminToken, setAdminToken } from './api.js';
import { API_URL } from './config.js';
import './admin.css';

const money = (n) => `${new Intl.NumberFormat('pt-MZ').format(Number(n || 0))} MT`;
const statusLabel = { pending:'Pendente', processing:'Processando', succeeded:'Pago', failed:'Falhou', refunded:'Reembolsado', cancelled:'Cancelado' };
const methodLabel = { mpesa:'M-Pesa', emola:'e-Mola', visa_card:'Visa Card' };

function loginError(err) {
  if (err.code === 'network') return `Sem ligação à API (${API_URL || 'endereço não definido'}). Verifique VITE_API_URL na Vercel e CORS_ORIGINS no Render.`;
  if (err.code === 'config' || err.code === 'bad_response') return `O endereço da API está errado (${API_URL || 'não definido'}). Verifique VITE_API_URL na Vercel.`;
  if (err.code === 'invalid_credentials') return 'Utilizador ou palavra-passe incorretos. Confirme que não há espaços a mais nem maiúscula automática (toque no olho para ver a palavra-passe).';
  if (err.code === 'admin_not_configured') return 'A administração não está configurada no servidor. No Render, defina ADMIN_USERNAME, ADMIN_PASSWORD e ADMIN_SESSION_SECRET e reinicie.';
  return err.message || 'Não foi possível entrar.';
}

// Rótulo do estado: um pagamento cancelado por falta de aprovação a tempo mostra "Expirado".
const txLabel = (r) => (r.status === 'cancelled' && r.failure_code === 'timeout' ? 'Expirado' : (statusLabel[r.status] || r.status));
const txClass = (r) => `status ${r.status}${r.status === 'cancelled' && r.failure_code === 'timeout' ? ' expired' : ''}`;

function Login({ onDone }) {
  const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [show,setShow]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await api('/admin/login',{method:'POST',body:{username,password}});setAdminToken(r.token);onDone();}catch(err){setError(loginError(err));}finally{setBusy(false)}}
  return <main className="admin-login"><form className="admin-login-card" onSubmit={submit}><div className="admin-mark">D</div><h1>Dumba Admin</h1><p>Acesso à operação da loja.</p><label>Utilizador<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" autoCapitalize="none" autoCorrect="off" spellCheck={false} required /></label><label>Palavra-passe<span className="pw-wrap"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" autoCapitalize="none" autoCorrect="off" spellCheck={false} required /><button type="button" className="pw-toggle" onClick={()=>setShow(v=>!v)} aria-label={show?'Ocultar palavra-passe':'Mostrar palavra-passe'} aria-pressed={show}>{show?'Ocultar':'Ver'}</button></span></label>{error&&<div className="admin-error">{error}</div>}<button className="admin-primary" disabled={busy}>{busy?'A entrar…':'Entrar'}</button></form></main>
}

function Shell({ children, page, setPage, unread, logout }) {
 return <div className="admin-shell"><aside><div className="admin-brand"><b>D</b><span>Dumba<small>Admin</small></span></div><nav><button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}>Visão geral</button><button className={page==='transactions'?'active':''} onClick={()=>setPage('transactions')}>Transações</button><button className={page==='notifications'?'active':''} onClick={()=>setPage('notifications')}>Notificações {unread>0&&<i>{unread}</i>}</button><button className={page==='integration'?'active':''} onClick={()=>setPage('integration')}>Integração</button></nav><button className="admin-logout" onClick={logout}>Sair</button></aside><section className="admin-main"><header className="admin-top"><div><small>DUMBA / ADMINISTRAÇÃO</small><h2>{page==='dashboard'?'Visão geral':page==='transactions'?'Transações':page==='notifications'?'Notificações':'Integração'}</h2></div><button className="admin-bell" onClick={()=>setPage('notifications')} aria-label="Notificações">◌{unread>0&&<span>{unread}</span>}</button></header>{children}</section></div>
}

function Dashboard({ setPage }) { const [s,setS]=useState(null); useEffect(()=>{api('/admin/summary').then(setS).catch(()=>{});},[]); return <div className="admin-content"><div className="admin-stats"><Stat label="Transações" value={s?.totalTransactions}/><Stat label="Pagamentos confirmados" value={s?.successfulTransactions}/><Stat label="Receita confirmada" value={s?money(s.revenueMzn):'—'}/><Stat label="A aguardar" value={s?.pendingTransactions}/></div><div className="admin-panel"><div className="panel-head"><div><h3>Operação de pagamentos</h3><p>Consulte o estado real das cobranças recebidas pelo gateway.</p></div><button className="admin-primary small" onClick={()=>setPage('transactions')}>Ver transações</button></div></div></div> }
function Stat({label,value}){return <div className="stat"><span>{label}</span><strong>{value??'—'}</strong></div>}

function Transactions({ onSelect }) { const [rows,setRows]=useState([]); const [status,setStatus]=useState(''); const [method,setMethod]=useState(''); const load=()=>api(`/admin/transactions?limit=100${status?`&status=${status}`:''}${method?`&method=${method}`:''}`).then(setRows).catch(()=>setRows([])); useEffect(()=>{load(); const id=setInterval(load,10000);return()=>clearInterval(id)},[status,method]); return <div className="admin-content"><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os estados</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Todos os métodos</option>{Object.entries(methodLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="admin-panel table-panel"><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Método</th><th>Valor</th><th>Estado</th><th>Referência</th><th>Data</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>onSelect(r.id)}><td><b>{r.code}</b><small>{r.customer_name}</small></td><td>{methodLabel[r.method]}</td><td>{money(r.amount_mzn)}</td><td><span className={txClass(r)}>{txLabel(r)}</span></td><td>{r.provider_reference||'—'}</td><td>{new Date(r.created_at).toLocaleString('pt-MZ')}</td></tr>)}{!rows.length&&<tr><td colSpan="6" className="empty-row">Sem transações.</td></tr>}</tbody></table></div></div></div> }

function TransactionDetail({ id, back }) { const [r,setR]=useState(null); useEffect(()=>{api(`/admin/transactions/${id}`).then(setR)},[id]); if(!r)return <div className="admin-content"><div className="admin-panel">A carregar…</div></div>; return <div className="admin-content"><button className="back" onClick={back}>← Voltar</button><div className="detail-grid"><div className="admin-panel"><div className="detail-top"><div><small>{r.code}</small><h3>{methodLabel[r.method]}</h3></div><span className={txClass(r)}>{txLabel(r)}</span></div><div className="detail-list"><p><span>Valor</span><b>{money(r.amount_mzn)}</b></p><p><span>Referência gateway</span><b>{r.provider_reference||'—'}</b></p><p><span>Estado do pedido</span><b>{r.order_status}</b></p><p><span>Pagamento</span><b>{statusLabel[r.payment_status]||r.payment_status}</b></p><p><span>Cliente</span><b>{r.customer_name}</b></p><p><span>Telemóvel</span><b>{r.phone}</b></p><p><span>Cidade</span><b>{r.city}</b></p><p><span>Criado</span><b>{new Date(r.created_at).toLocaleString('pt-MZ')}</b></p></div>{r.status==='succeeded'&&<a className="admin-secondary invoice-link" href={`${API_URL}/api/orders/${encodeURIComponent(r.code)}/invoice`} target="_blank" rel="noopener noreferrer">Descarregar fatura (PDF)</a>}{r.failure_message&&<div className="admin-error">{r.failure_message}</div>}</div><div className="admin-panel"><h3>Resposta do gateway</h3><pre>{JSON.stringify(r.raw_response,null,2)}</pre></div></div></div> }

function Notifications({ refresh }) { const [data,setData]=useState({items:[],unread:0}); const load=()=>api('/admin/notifications').then(setData).catch(()=>{}); useEffect(()=>{load();const id=setInterval(load,8000);return()=>clearInterval(id)},[]); async function read(ids){await api('/admin/notifications/read',{method:'POST',body:ids?{ids}:{} });load();refresh()} return <div className="admin-content"><div className="panel-head"><div><h3>Centro de notificações</h3><p>Eventos importantes de pedidos e pagamentos.</p></div><button className="admin-secondary" onClick={()=>read()}>Marcar tudo como lido</button></div><div className="notification-list">{data.items.map(n=><button key={n.id} className={`notification ${!n.read_at?'unread':''}`} onClick={()=>!n.read_at&&read([n.id])}><span className={`notification-dot ${n.type}`}/><span><b>{n.title}</b><small>{n.message}</small><time>{new Date(n.created_at).toLocaleString('pt-MZ')}</time></span></button>)}{!data.items.length&&<div className="admin-panel">Sem notificações.</div>}</div></div> }

function Integration(){const [d,setD]=useState(null);useEffect(()=>{api('/admin/integration').then(setD).catch(()=>{})},[]);return <div className="admin-content"><div className="admin-panel"><div className="panel-head"><div><h3>ZumboPay</h3><p>As chaves permanecem exclusivamente no backend.</p></div><span className={`status ${d?.configured?'succeeded':'failed'}`}>{d?.configured?'Configurado':'Incompleto'}</span></div>{d&&<div className="detail-list"><p><span>API</span><b>{d.apiUrl}</b></p><p><span>Merchant ID</span><b>{d.merchantId||'—'}</b></p><p><span>M-Pesa wallet</span><b>{d.wallets.mpesa?'Configurada':'Em falta'}</b></p><p><span>e-Mola wallet</span><b>{d.wallets.emola?'Configurada':'Em falta'}</b></p><p><span>Card wallet</span><b>{d.wallets.card?'Configurada':'Em falta'}</b></p></div>}</div></div>}

export default function AdminApp(){const [auth,setAuth]=useState(null);const [page,setPage]=useState('dashboard');const [detail,setDetail]=useState(null);const [unread,setUnread]=useState(0);const refresh=()=>api('/admin/notifications').then(d=>setUnread(d.unread)).catch(()=>{});useEffect(()=>{if(!getAdminToken()){setAuth(false);return}api('/admin/me').then(d=>setAuth(d.authenticated)).catch(()=>setAuth(false))},[]);useEffect(()=>{const off=()=>setAuth(false);window.addEventListener('dumba:admin-unauthorized',off);return()=>window.removeEventListener('dumba:admin-unauthorized',off)},[]);useEffect(()=>{if(auth)refresh()},[auth]);if(auth===null)return <div className="admin-loading">A carregar…</div>;if(!auth)return <Login onDone={()=>setAuth(true)}/>;async function logout(){try{await api('/admin/logout',{method:'POST'})}catch{}setAdminToken(null);setAuth(false)}let content=page==='dashboard'?<Dashboard setPage={setPage}/>:page==='transactions'?(detail?<TransactionDetail id={detail} back={()=>setDetail(null)}/>:<Transactions onSelect={setDetail}/>):page==='notifications'?<Notifications refresh={refresh}/>:<Integration/>;return <Shell page={page} setPage={(p)=>{setPage(p);setDetail(null)}} unread={unread} logout={logout}>{content}</Shell>}
